### ISSUE TITLE
Faraday::ConnectionFailed execution expired

### ISSUE THREAD

**Issue by OrrYakobiStudent** [omniauth/omniauth-oauth2#106]
I cannot figure why I keep getting the following error:

```
Faraday::ConnectionFailed (execution expired):

socksify (1.7.1) lib/socksify.rb:178:in `initialize'
socksify (1.7.1) lib/socksify.rb:178:in `initialize'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `open'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:876:in `start'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:80:in `perform_request'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:38:in `block in call'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:33:in `call'
faraday (0.12.2) lib/faraday/request/url_encoded.rb:15:in `call'
faraday (0.12.2) lib/faraday/rack_builder.rb:141:in `build_response'
faraday (0.12.2) lib/faraday/connection.rb:386:in `run_request'
oauth2 (1.4.0) lib/oauth2/client.rb:99:in `request'
oauth2 (1.4.0) lib/oauth2/client.rb:146:in `get_token'
oauth2 (1.4.0) lib/oauth2/strategy/auth_code.rb:30:in `get_token'
omniauth-google-oauth2 (0.5.1) lib/omniauth/strategies/google_oauth2.rb:120:in `get_access_token'
omniauth-google-oauth2 (0.5.1) lib/omniauth/strategies/google_oauth2.rb:94:in `custom_build_access_token'
omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:73:in `callback_phase'
omniauth (1.6.1) lib/omniauth/strategy.rb:230:in `callback_call'
omniauth (1.6.1) lib/omniauth/strategy.rb:187:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I believe it is being caused somewhere around here: 
```
oauth2 (1.4.0) lib/oauth2/client.rb:99:in `request'
oauth2 (1.4.0) lib/oauth2/client.rb:146:in `get_token'
oauth2 (1.4.0) lib/oauth2/strategy/auth_code.rb:30:in `get_token'
```

Probably in get_token.

**Comment by richardrails** [comment]
+1

**Comment by richardrails** [comment]
any progress with this?

**Comment by tmilewski** [comment]
While I'd love to help out, `omniauth-oauth2` doesn't appear to be the one causing the issue. This issue is better suited for [oauth-xx/oauth2](https://github.com/oauth-xx/oauth2/).
